// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2eTZveeilZTj5oRuK9mx-nWNyt2Ek6bU',
    appId: '1:614994770036:web:c5f770d4a4ae84d11cb921',
    messagingSenderId: '614994770036',
    projectId: 'nutriscan-f84b0',
    authDomain: 'nutriscan-f84b0.firebaseapp.com',
    storageBucket: 'nutriscan-f84b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlBjo7hpd-PRZ2MteR57fxexovynGknY',
    appId: '1:614994770036:android:826d280fc345b27e1cb921',
    messagingSenderId: '614994770036',
    projectId: 'nutriscan-f84b0',
    storageBucket: 'nutriscan-f84b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT9HvkT9y9_i7CvuVWpiA52iIGHKlkF2s',
    appId: '1:614994770036:ios:cb6ca09191af3f4d1cb921',
    messagingSenderId: '614994770036',
    projectId: 'nutriscan-f84b0',
    storageBucket: 'nutriscan-f84b0.firebasestorage.app',
    iosBundleId: 'com.example.nutriScanDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT9HvkT9y9_i7CvuVWpiA52iIGHKlkF2s',
    appId: '1:614994770036:ios:cb6ca09191af3f4d1cb921',
    messagingSenderId: '614994770036',
    projectId: 'nutriscan-f84b0',
    storageBucket: 'nutriscan-f84b0.firebasestorage.app',
    iosBundleId: 'com.example.nutriScanDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2eTZveeilZTj5oRuK9mx-nWNyt2Ek6bU',
    appId: '1:614994770036:web:48be3627c7bcac4c1cb921',
    messagingSenderId: '614994770036',
    projectId: 'nutriscan-f84b0',
    authDomain: 'nutriscan-f84b0.firebaseapp.com',
    storageBucket: 'nutriscan-f84b0.firebasestorage.app',
  );
}
